# Generated by Django 4.2.4 on 2023-09-04 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stafi', '0003_alter_kurset_leksioni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kurset',
            name='kredite',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='kurset',
            name='leksioni',
            field=models.FileField(max_length=2080, upload_to=''),
        ),
    ]
