# Generated by Django 4.2.4 on 2023-09-04 16:41

from django.db import migrations, models
import django.db.models.deletion
import stafi.models


class Migration(migrations.Migration):

    dependencies = [
        ('stafi', '0005_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='kurset',
            name='subject',
            field=models.ForeignKey(default=stafi.models.get_or_create_default_subject, on_delete=django.db.models.deletion.CASCADE, to='stafi.subject'),
        ),
    ]
