# Generated by Django 4.2.4 on 2023-11-18 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stafi', '0011_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
